<?php

namespace ContestBundle\Repository;

/**
 * FiletypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FiletypeRepository extends \Doctrine\ORM\EntityRepository
{
}
